package com.teus.projectrpg.injury.type

enum class InjuryType {
    MINOR_TORN_MUSCLE,
    MAJOR_TORN_MUSCLE,
    MINOR_BROKEN_BONE,
    MAJOR_BROKEN_BONE,
    AMPUTATED_ARM,
    AMPUTATED_EAR,
    AMPUTATED_EYE,
    AMPUTATED_FINGERS,
    AMPUTATED_FOOT,
    AMPUTATED_HAND,
    AMPUTATED_LEG,
    AMPUTATED_NOSE,
    AMPUTATED_TEETH,
    AMPUTATED_TOES,
    AMPUTATED_TONGUE,
}